import type { Category } from "@shared/schema";

export const categories: Category[] = [
  {
    id: "attractions",
    title: "Tourist Places",
    titleAr: "الأماكن السياحية",
    icon: "MapPin",
    description: "اكتشف أجمل المعالم السياحية",
    color: "from-amber-600/80 to-amber-800/90",
  },
  {
    id: "hotels",
    title: "Hotels",
    titleAr: "الفنادق",
    icon: "Building2",
    description: "أفضل أماكن الإقامة",
    color: "from-stone-600/80 to-stone-800/90",
  },
  {
    id: "restaurants",
    title: "Restaurants",
    titleAr: "المطاعم",
    icon: "UtensilsCrossed",
    description: "تذوق ألذ المأكولات",
    color: "from-orange-600/80 to-orange-800/90",
  },
  {
    id: "hiking",
    title: "Hiking Trips",
    titleAr: "رحلات الهايكنق",
    icon: "Mountain",
    description: "مغامرات في الطبيعة",
    color: "from-emerald-700/80 to-emerald-900/90",
  },
  {
    id: "taxis",
    title: "Taxis",
    titleAr: "سيارات الأجرة",
    icon: "Car",
    description: "تنقل بسهولة وراحة",
    color: "from-yellow-600/80 to-yellow-800/90",
  },
  {
    id: "hospitals",
    title: "Hospitals",
    titleAr: "المستشفيات",
    icon: "Hospital",
    description: "مراكز صحية ومستشفيات",
    color: "from-red-600/80 to-red-800/90",
  },
  {
    id: "tour-guides",
    title: "Tour Guides",
    titleAr: "المرشدين السياحيين",
    icon: "UserCheck",
    description: "مرشدين محترفين لجولاتك",
    color: "from-teal-600/80 to-teal-800/90",
  },
  {
    id: "shoumatak",
    title: "Shoumatak",
    titleAr: "شومتك",
    icon: "Sparkles",
    description: "خطط رحلتك المثالية",
    color: "from-primary/80 to-primary/95",
  },
  {
    id: "nearby",
    title: "Nearby Places",
    titleAr: "الأماكن القريبة مني",
    icon: "Navigation",
    description: "اكتشف الأماكن القريبة من موقعك",
    color: "from-blue-600/80 to-blue-800/90",
  },
  {
    id: "activities",
    title: "Activities & Seasons",
    titleAr: "الأنشطة والمواسم",
    icon: "Compass",
    description: "أنشطة ومواسم سياحية متنوعة",
    color: "from-purple-600/80 to-purple-800/90",
  },
  {
    id: "hidden-gems",
    title: "Shouma Paths",
    titleAr: "دروب شومة",
    icon: "Gem",
    description: "أماكن سياحية مخفية وغير معروفة",
    color: "from-rose-600/80 to-rose-800/90",
  },
  {
    id: "offline-map",
    title: "Offline Map",
    titleAr: "خريطة بدون نت",
    icon: "Map",
    description: "خريطة تفاعلية تعمل بدون إنترنت",
    color: "from-cyan-600/80 to-cyan-800/90",
  },
  {
    id: "group-trips",
    title: "Group Trips",
    titleAr: "رحلات جماعية",
    icon: "Users",
    description: "خطط رحلتك الجماعية واحصل على عرض مخصص",
    color: "from-indigo-600/80 to-indigo-800/90",
  },
  {
    id: "himam-shouma",
    title: "Himam Shouma",
    titleAr: "همم شومة",
    icon: "Accessibility",
    description: "خدمات ومواقع مهيأة لأصحاب الهمم",
    color: "from-sky-600/80 to-sky-800/90",
  },
];
