import hospitalRoyalImg from "@/assets/hospital-royal.png";
import hospitalKhoulaImg from "@/assets/hospital-khoula.png";
import hospitalBadrSamaaImg from "@/assets/hospital-badr-samaa.png";
import hospitalSquImg from "@/assets/hospital-squ.png";
import hospitalOmanInternationalImg from "@/assets/hospital-oman-international.png";

export interface Hospital {
  id: string;
  name: string;
  nameAr: string;
  type: "hospital" | "health_center" | "clinic" | "pharmacy";
  typeAr: string;
  location: string;
  address?: string;
  region: string;
  description: string;
  services: string[];
  phone: string;
  emergencyPhone?: string;
  workingHours: string;
  image: string;
  rating: number;
  isGovernment: boolean;
  mapUrl?: string;
}

export const getTypeAr = (type: string): string => {
  const types: Record<string, string> = {
    hospital: "مستشفى",
    health_center: "مركز صحي",
    clinic: "عيادة",
    pharmacy: "صيدلية",
  };
  return types[type] || type;
};

export const getTypeColor = (type: string): string => {
  const colors: Record<string, string> = {
    hospital: "bg-red-600 text-white",
    health_center: "bg-blue-600 text-white",
    clinic: "bg-green-600 text-white",
    pharmacy: "bg-purple-600 text-white",
  };
  return colors[type] || "bg-gray-600 text-white";
};

export const hospitals: Hospital[] = [
  {
    id: "royal-hospital",
    name: "Royal Hospital",
    nameAr: "المستشفى السلطاني",
    type: "hospital",
    typeAr: "مستشفى حكومي",
    location: "مسقط",
    address: "Ghala St, Muscat",
    region: "محافظة مسقط",
    description: "المستشفى السلطاني هو أكبر مستشفى حكومي في سلطنة عمان، يقدم خدمات طبية متكاملة ومتخصصة على أعلى مستوى. يضم المستشفى أقسام متعددة تشمل الطوارئ، الجراحة، الباطنية، القلب، الأورام، وغيرها من التخصصات الطبية.",
    services: ["طوارئ 24 ساعة", "جراحة عامة", "قسم القلب", "الأورام", "العناية المركزة", "الأشعة", "المختبرات"],
    phone: "+968 24 599000",
    emergencyPhone: "+968 24599999",
    workingHours: "24 ساعة",
    image: hospitalRoyalImg,
    rating: 4.5,
    isGovernment: true,
    mapUrl: "https://maps.app.goo.gl/SX9FH4oYC2PKH3PL9",
  },
  {
    id: "squ-hospital",
    name: "Sultan Qaboos University Hospital",
    nameAr: "مستشفى جامعة السلطان قابوس",
    type: "hospital",
    typeAr: "مستشفى حكومي",
    location: "السيب، مسقط",
    address: "H5QC+36M, Dr Ali Al Bimani St, Seeb",
    region: "محافظة مسقط",
    description: "مستشفى جامعة السلطان قابوس هو مستشفى تعليمي تابع لجامعة السلطان قابوس. يقدم خدمات طبية متقدمة ويعتبر من أهم المراكز الطبية التعليمية في السلطنة.",
    services: ["طوارئ 24 ساعة", "جراحة عامة", "قسم القلب", "الأورام", "العناية المركزة", "الأشعة", "المختبرات", "طب الأسرة"],
    phone: "+968 24 147777",
    emergencyPhone: "+968 24 147777",
    workingHours: "24 ساعة",
    image: hospitalSquImg,
    rating: 4.6,
    isGovernment: true,
    mapUrl: "https://maps.app.goo.gl/Rr3euq7R41zdQBim7",
  },
  {
    id: "oman-international-hospital",
    name: "Oman International Hospital",
    nameAr: "مستشفى عمان الدولي",
    type: "hospital",
    typeAr: "مستشفى خاص",
    location: "مسقط",
    address: "Al Dhayafa St, Muscat 333",
    region: "محافظة مسقط",
    description: "مستشفى عمان الدولي هو مستشفى خاص حديث يقدم خدمات طبية متكاملة بمعايير دولية عالية. يضم أحدث التجهيزات الطبية وفريق من الأطباء المتخصصين.",
    services: ["طوارئ 24 ساعة", "جراحة عامة", "قسم القلب", "العظام", "العناية المركزة", "الأشعة", "المختبرات"],
    phone: "+968 24 903500",
    emergencyPhone: "+968 24 903500",
    workingHours: "24 ساعة",
    image: hospitalOmanInternationalImg,
    rating: 4.5,
    isGovernment: false,
    mapUrl: "https://maps.app.goo.gl/1He7emPqvJC9X67F8",
  },
  {
    id: "khoula-hospital",
    name: "Khoula Hospital",
    nameAr: "مستشفى خولة",
    type: "hospital",
    typeAr: "مستشفى حكومي",
    location: "مسقط",
    address: "شارع الفحل, Muscat",
    region: "محافظة مسقط",
    description: "مستشفى خولة هو مستشفى حكومي متخصص في جراحة العظام والحوادث. يعتبر المركز الرئيسي لعلاج إصابات الحوادث في السلطنة ويقدم خدمات طبية متميزة في مجال جراحة العظام.",
    services: ["طوارئ 24 ساعة", "جراحة العظام", "علاج الحوادث", "العلاج الطبيعي", "العناية المركزة", "الأشعة"],
    phone: "+968 22 501000",
    emergencyPhone: "+968 24563600",
    workingHours: "24 ساعة",
    image: hospitalKhoulaImg,
    rating: 4.3,
    isGovernment: true,
    mapUrl: "https://maps.app.goo.gl/hsjeGEnYaEVFti8Z7",
  },
  {
    id: "muscat-private-hospital",
    name: "Muscat Private Hospital",
    nameAr: "مستشفى مسقط الخاص",
    type: "hospital",
    typeAr: "مستشفى خاص",
    location: "بوشر، مسقط",
    region: "محافظة مسقط",
    description: "مستشفى مسقط الخاص هو أحد أبرز المستشفيات الخاصة في السلطنة، يقدم خدمات طبية شاملة بمعايير عالمية. يتميز بتقديم رعاية صحية متميزة مع طاقم طبي متخصص.",
    services: ["طوارئ 24 ساعة", "جراحة عامة", "طب الأطفال", "النساء والولادة", "الأسنان", "العيون", "الجلدية"],
    phone: "+968 24583600",
    emergencyPhone: "+968 24583699",
    workingHours: "24 ساعة",
    image: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800",
    rating: 4.6,
    isGovernment: false,
  },
  {
    id: "nizwa-hospital",
    name: "Nizwa Hospital",
    nameAr: "مستشفى نزوى",
    type: "hospital",
    typeAr: "مستشفى حكومي",
    location: "نزوى",
    region: "محافظة الداخلية",
    description: "مستشفى نزوى المرجعي هو المستشفى الرئيسي في محافظة الداخلية، يقدم خدمات طبية متكاملة لسكان المحافظة والمناطق المجاورة. يضم تخصصات متعددة ويعمل على مدار الساعة.",
    services: ["طوارئ 24 ساعة", "جراحة عامة", "الباطنية", "طب الأطفال", "النساء والولادة", "المختبرات"],
    phone: "+968 25431355",
    emergencyPhone: "+968 25431300",
    workingHours: "24 ساعة",
    image: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=800",
    rating: 4.2,
    isGovernment: true,
  },
  {
    id: "sohar-hospital",
    name: "Sohar Hospital",
    nameAr: "مستشفى صحار",
    type: "hospital",
    typeAr: "مستشفى حكومي",
    location: "صحار",
    region: "محافظة شمال الباطنة",
    description: "مستشفى صحار هو المستشفى المرجعي لمحافظة شمال الباطنة، يقدم خدمات طبية شاملة ومتخصصة. يتميز بموقعه الاستراتيجي وتقديم رعاية صحية عالية الجودة.",
    services: ["طوارئ 24 ساعة", "جراحة عامة", "القلب", "الباطنية", "طب الأطفال", "العظام"],
    phone: "+968 26840399",
    emergencyPhone: "+968 26840300",
    workingHours: "24 ساعة",
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800",
    rating: 4.1,
    isGovernment: true,
  },
  {
    id: "salalah-hospital",
    name: "Sultan Qaboos Hospital Salalah",
    nameAr: "مستشفى السلطان قابوس بصلالة",
    type: "hospital",
    typeAr: "مستشفى حكومي",
    location: "صلالة",
    region: "محافظة ظفار",
    description: "مستشفى السلطان قابوس بصلالة هو المستشفى المرجعي لمحافظة ظفار، يقدم خدمات طبية متكاملة لسكان المحافظة. يضم تخصصات طبية متعددة ويعمل على مدار الساعة.",
    services: ["طوارئ 24 ساعة", "جراحة عامة", "الباطنية", "طب الأطفال", "النساء والولادة", "القلب", "الأورام"],
    phone: "+968 23211555",
    emergencyPhone: "+968 23211500",
    workingHours: "24 ساعة",
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800",
    rating: 4.4,
    isGovernment: true,
  },
  {
    id: "al-nahda-hospital",
    name: "Al Nahda Hospital",
    nameAr: "مستشفى النهضة",
    type: "hospital",
    typeAr: "مستشفى حكومي",
    location: "مسقط",
    region: "محافظة مسقط",
    description: "مستشفى النهضة هو مستشفى حكومي متخصص في أمراض النساء والولادة وطب الأطفال. يعتبر من أهم المراكز المتخصصة في هذا المجال في السلطنة.",
    services: ["النساء والولادة", "طب الأطفال", "حديثي الولادة", "العناية المركزة", "المختبرات", "الأشعة"],
    phone: "+968 24837800",
    emergencyPhone: "+968 24837899",
    workingHours: "24 ساعة",
    image: "https://images.unsplash.com/photo-1551076805-e1869033e561?w=800",
    rating: 4.5,
    isGovernment: true,
  },
  {
    id: "al-buraimi-hospital",
    name: "Al Buraimi Hospital",
    nameAr: "مستشفى البريمي",
    type: "hospital",
    typeAr: "مستشفى حكومي",
    location: "البريمي",
    region: "محافظة البريمي",
    description: "مستشفى البريمي هو المستشفى الرئيسي في محافظة البريمي، يقدم خدمات طبية متكاملة لسكان المحافظة. يتميز بموقعه على الحدود ويخدم المنطقة بكفاءة.",
    services: ["طوارئ 24 ساعة", "جراحة عامة", "الباطنية", "طب الأطفال", "النساء والولادة", "المختبرات"],
    phone: "+968 25652066",
    emergencyPhone: "+968 25652000",
    workingHours: "24 ساعة",
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800",
    rating: 4.0,
    isGovernment: true,
  },
  {
    id: "badr-al-samaa-muscat",
    name: "Badr Al Samaa Hospital",
    nameAr: "مستشفى بدر السماء",
    type: "hospital",
    typeAr: "مستشفى خاص",
    location: "السيب، مسقط",
    address: "P. B. No. 1165, Seeb 121",
    region: "محافظة مسقط",
    description: "مستشفى بدر السماء هو مجموعة مستشفيات خاصة رائدة في السلطنة، تقدم خدمات طبية شاملة بأسعار معقولة. تتميز بانتشارها في عدة مدن عمانية.",
    services: ["طوارئ 24 ساعة", "جراحة عامة", "الأسنان", "العيون", "الجلدية", "المختبرات", "الصيدلية"],
    phone: "+968 21 142600",
    emergencyPhone: "+968 24799700",
    workingHours: "24 ساعة",
    image: hospitalBadrSamaaImg,
    rating: 4.2,
    isGovernment: false,
    mapUrl: "https://maps.app.goo.gl/6uG8wPu5CadLFNSz7",
  },
  {
    id: "al-hayat-health-center",
    name: "Al Hayat Health Center",
    nameAr: "مركز الحياة الصحي",
    type: "health_center",
    typeAr: "مركز صحي",
    location: "السيب، مسقط",
    region: "محافظة مسقط",
    description: "مركز الحياة الصحي هو مركز صحي متكامل يقدم خدمات الرعاية الصحية الأولية للمجتمع. يتميز بتقديم خدمات طبية عالية الجودة بأسعار مناسبة.",
    services: ["الطب العام", "طب الأسرة", "التطعيمات", "رعاية الحوامل", "الأسنان", "المختبرات"],
    phone: "+968 24423355",
    workingHours: "السبت - الخميس: 8 صباحاً - 10 مساءً",
    image: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800",
    rating: 4.3,
    isGovernment: false,
  },
  {
    id: "ibri-hospital",
    name: "Ibri Hospital",
    nameAr: "مستشفى عبري",
    type: "hospital",
    typeAr: "مستشفى حكومي",
    location: "عبري",
    region: "محافظة الظاهرة",
    description: "مستشفى عبري هو المستشفى المرجعي لمحافظة الظاهرة، يقدم خدمات طبية شاملة لسكان المحافظة والمناطق المجاورة.",
    services: ["طوارئ 24 ساعة", "جراحة عامة", "الباطنية", "طب الأطفال", "النساء والولادة", "العظام"],
    phone: "+968 25691433",
    emergencyPhone: "+968 25691400",
    workingHours: "24 ساعة",
    image: "https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?w=800",
    rating: 4.1,
    isGovernment: true,
  },
  {
    id: "sur-hospital",
    name: "Sur Hospital",
    nameAr: "مستشفى صور",
    type: "hospital",
    typeAr: "مستشفى حكومي",
    location: "صور",
    region: "محافظة جنوب الشرقية",
    description: "مستشفى صور هو المستشفى المرجعي لمحافظة جنوب الشرقية، يقدم خدمات طبية متكاملة ويخدم سكان الساحل الشرقي.",
    services: ["طوارئ 24 ساعة", "جراحة عامة", "الباطنية", "طب الأطفال", "النساء والولادة", "المختبرات"],
    phone: "+968 25543011",
    emergencyPhone: "+968 25543000",
    workingHours: "24 ساعة",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800",
    rating: 4.0,
    isGovernment: true,
  },
];
