import type { Restaurant } from "@shared/schema";
import alburjCafeImg from "@/assets/alburj-cafe.png";
import lagunaCafeImg from "@/assets/laguna-cafe.png";
import baitAlmadghootImg from "@/assets/bait-almadghoot.png";
import musandamFanrImg from "@/assets/musandam-fanr.png";
import tamraNizwaImg from "@/assets/tamra-nizwa.png";
import greekHouseImg from "@/assets/greek-house.png";
import alhawashImg from "@/assets/alhawash.png";
import souqDuqmImg from "@/assets/souq-duqm.png";
import ainAlkhaleejImg from "@assets/image_1772573893188.png";
import binAteeqImg from "@assets/image_1772574323731.png";
import cafeBateelImg from "@assets/image_1772603776289.png";
import darcysKitchenImg from "@assets/image_1772604487806.png";

export const restaurants: Restaurant[] = [
  {
    id: "1",
    name: "Al Burj Cafe",
    nameAr: "قهوة البرج",
    description: "يُعد قهوة البرج من الوجهات المميزة التي تجمع بين عبق الماضي والجمال المعماري، حيث يقع في قلب المعالم التاريخية. يشتهر بتقديم القهوة العمانية الأصيلة والوجبات الخفيفة والحلويات في أجواء تراثية ساحرة، مما يجعله محطة رائعة للزوار الراغبين في الاستراحة أثناء استكشاف المعالم التاريخية المحيطة.",
    city: "ولاية الرستاق",
    region: "محافظة جنوب الباطنة",
    image: alburjCafeImg,
    cuisine: "مقهى تراثي",
    priceRange: "moderate",
    rating: 4.7,
    features: ["قهوة عمانية", "حلويات", "أجواء تراثية", "إطلالة تاريخية"],
    mapUrl: "https://maps.app.goo.gl/aE2wXbBCtjyMWHGy8",
  },
  {
    id: "2",
    name: "Laguna",
    nameAr: "لاجونا",
    description: "يُعد لاجونا وجهة عصرية وشهيرة، ويُعرف بكونه مطعماً ومقهى يقدم تشكيلة متنوعة من المأكولات والمشروبات، بما في ذلك الحلويات والوجبات الخفيفة والقهوة المختصة. يتميز المكان بجلساته المريحة وتصميمه الجذاب، مما يجعله مكاناً مفضلاً للقاءات الأصدقاء والعائلات، خاصة في الفترة المسائية.",
    city: "ولاية السيب",
    region: "محافظة مسقط",
    image: lagunaCafeImg,
    cuisine: "مقهى عصري",
    priceRange: "moderate",
    rating: 4.6,
    features: ["قهوة مختصة", "حلويات", "جلسات مريحة", "تصميم عصري"],
    mapUrl: "https://maps.app.goo.gl/fK4bAFdDjVxmm1Tw9",
  },
  {
    id: "3",
    name: "Bait Al Madhgoot",
    nameAr: "بيت المضغوط",
    description: "يعتبر مطعم بيت المضغوط في البريمي وجهة مفضلة لمحبي الأكلات الشعبية، حيث يتخصص في تقديم طبق \"المضغوط\" بطعمه الأصيل. يتميز المطعم بجودة مكوناته من اللحوم والأرز واستخدام التوابل التقليدية التي تمنحه مذاقاً خاصاً. كما يشتهر المطعم بنظافته وخدمته السريعة، مما يجعله خياراً ممتازاً للوجبات العائلية أو الولائم.",
    city: "ولاية البريمي",
    region: "محافظة البريمي",
    image: baitAlmadghootImg,
    cuisine: "عُماني شعبي",
    priceRange: "budget",
    rating: 4.5,
    features: ["مضغوط أصيل", "خدمة سريعة", "مناسب للعائلات", "نظافة عالية"],
    mapUrl: "https://maps.app.goo.gl/3dnwRzzrJgDdqJmWA",
  },
  {
    id: "4",
    name: "Musandam Fanr Restaurant",
    nameAr: "مطعم فنر مسندم",
    description: "يُعد مطعم فنر مسندم من المطاعم المعروفة في مدينة خصب، ويشتهر بتقديم تشكيلة متنوعة من المأكولات، وخاصة الأطباق البحرية الطازجة التي تشتهر بها المنطقة، بالإضافة إلى الأطباق العربية والآسيوية. يتميز المطعم بموقعه القريب من الميناء والخدمات السياحية، ويحظى بتقييمات جيدة لنظافته وجودة طعمه، مما يجعله وجهة مفضلة للسياح الراغبين في تجربة المذاق المحلي بعد جولات القوارب في أخوار مسندم.",
    city: "ولاية خصب",
    region: "محافظة مسندم",
    image: musandamFanrImg,
    cuisine: "مأكولات بحرية",
    priceRange: "moderate",
    rating: 4.5,
    features: ["أسماك طازجة", "قريب من الميناء", "أطباق آسيوية", "نظافة عالية"],
    mapUrl: "https://maps.app.goo.gl/FJ2A6Ny3QA6iuE6G9",
  },
  {
    id: "5",
    name: "Tamra Restaurant & Cafe",
    nameAr: "مطعم ومقهى تمرة",
    description: "يُعد مطعم ومقهى تمرة وجهة سياحية وتراثية رائعة، حيث يتميز بموقعه الاستراتيجي المقابل لقلعة نزوى التاريخية. يقدم المطعم تجربة طعام عمانية وعالمية في أجواء تمزج بين الحداثة والتراث، ويشتهر بإطلالته الخلابة على سوق وقلعة نزوى من الشرفة (السطح)، مما يجعله مكاناً مثالية لتناول القهوة العمانية أو وجبات الغداء والعشاء أثناء زيارة المعالم الأثرية.",
    city: "ولاية نزوى",
    region: "محافظة الداخلية",
    image: tamraNizwaImg,
    cuisine: "عُماني وعالمي",
    priceRange: "moderate",
    rating: 4.7,
    features: ["إطلالة على قلعة نزوى", "شرفة سطحية", "قهوة عمانية", "أجواء تراثية"],
    mapUrl: "https://maps.app.goo.gl/iQhbrUE5GYcr4UgA7",
  },
  {
    id: "6",
    name: "Greek House Restaurant",
    nameAr: "مطعم البيت اليوناني",
    description: "يُعد مطعم البيت اليوناني من المطاعم المميزة والفريدة في المنطقة، حيث يقدم تجربة طعام مستوحاة من المطبخ اليوناني والمتوسطي في قلب البيئة الصحراوية. يشتهر بتقديم أطباق المشاوي، السلطات اليونانية، والمأكولات المطهوة بطرق تقليدية تحافظ على النكهة الأصلية. يتميز المطعم بتصميمه البسيط والجميل الذي يمنح الزوار أجواءً هادئة ومريحة، وهو محطة مفضلة للسياح المتوجهين إلى رمال الشرقية.",
    city: "ولاية بدية",
    region: "محافظة شمال الشرقية",
    image: greekHouseImg,
    cuisine: "يوناني ومتوسطي",
    priceRange: "moderate",
    rating: 4.6,
    features: ["مشاوي يونانية", "سلطات طازجة", "أجواء هادئة", "قريب من رمال الشرقية"],
    mapUrl: "https://maps.app.goo.gl/iBjkQYUroDHrUfBM7",
  },
  {
    id: "7",
    name: "Al Hawash Restaurant",
    nameAr: "مطعم الحوش",
    description: "يُعد مطعم الحوش تجربة ثقافية وغذائية فريدة، حيث يقع في بيت أثري قديم تم ترميمه ليصبح مطعماً يقدم الأكلات العمانية التقليدية بلمسة عصرية. يتميز المكان بجلساته التراثية الرائعة التي تطل مباشرة على البحر (خور البطح)، مما يوفر أجواءً ساحرة للزوار. يشتهر المطعم بتقديم وجبات الفطور العماني المبتكر، والمشاوي، والحلويات المحلية، ويعتبر من الوجهات السياحية الأبرز في المنطقة لمحبي التاريخ والطعام الأصيل.",
    city: "ولاية صور",
    region: "محافظة جنوب الشرقية",
    image: alhawashImg,
    cuisine: "عُماني تقليدي",
    priceRange: "moderate",
    rating: 4.8,
    features: ["بيت أثري", "إطلالة بحرية", "فطور عماني", "حلويات محلية"],
    mapUrl: "https://maps.app.goo.gl/p1tEFksfA1UUR9bY6",
  },
  {
    id: "8",
    name: "Souq Restaurant - Duqm",
    nameAr: "مطعم سوق - الدقم",
    description: "يُعد مطعم سوق أحد المطاعم الرئيسية في ولاية الدقم، ويتميز بتصميمه الذي يحاكي الأسواق العمانية التقليدية. يقدم المطعم تجربة طعام متنوعة تشمل بوفيهات عالمية ومحلية، ويشتهر بتقديم وجبات الإفطار والغداء والعشاء في أجواء مريحة وراقية. يقع المطعم ضمن مرافق فندقية كبرى، مما يجعله وجهة مفضلة للعاملين في المنطقة والسياح.",
    city: "ولاية الدقم",
    region: "محافظة الوسطى",
    image: souqDuqmImg,
    cuisine: "عالمي ومحلي",
    priceRange: "moderate",
    rating: 4.5,
    features: ["تصميم السوق التقليدي", "بوفيهات متنوعة", "أجواء راقية", "مرافق فندقية"],
    mapUrl: "https://maps.app.goo.gl/tjt2RSz16ScJEgH56",
  },
  {
    id: "9",
    name: "Bait Al Luban",
    nameAr: "بيت اللبان",
    description: "مطعم عُماني أصيل في قلب مطرح يقدم أطباقاً تقليدية بنكهة عُمانية خالصة. جرب الشوا والمقبوس في أجواء تراثية فريدة.",
    city: "مسقط",
    region: "محافظة مسقط",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=800",
    cuisine: "عُماني تقليدي",
    priceRange: "moderate",
    rating: 4.7,
    features: ["طعام تقليدي", "أجواء تراثية", "خدمة ممتازة", "حلويات عُمانية"],
    mapUrl: "https://maps.app.goo.gl/swZVokqKTjfzw5JB9",
  },
  {
    id: "10",
    name: "Al Mandoos",
    nameAr: "المندوس",
    description: "مطعم في فندق الريتز كارلتون يقدم رحلة طهي عبر المطبخ العُماني التقليدي في أجواء فخمة وتصميم تراثي أنيق.",
    city: "مسقط",
    region: "محافظة مسقط",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=800",
    cuisine: "عُماني فاخر",
    priceRange: "luxury",
    rating: 4.8,
    features: ["فندق 5 نجوم", "تصميم تراثي", "قائمة تذوق", "خدمة استثنائية"],
    mapUrl: "https://maps.app.goo.gl/ADvaEWmJ27x5TWxY6",
  },
  {
    id: "11",
    name: "Ain Al Khaleej Restaurant",
    nameAr: "مطعم ومطبخ عين الخليج",
    description: "يُعد مطعم ومطبخ عين الخليج من المطاعم الشعبية المعروفة في ولاية المضيبي، ويشتهر بتقديم الأطباق العمانية التقليدية والمأكولات الشعبية بنكهة أصيلة. يتميز المطعم بوجباته المنزلية الطازجة وأسعاره المناسبة، مما يجعله وجهة مفضلة للعائلات والمسافرين في محافظة شمال الشرقية.",
    city: "ولاية المضيبي",
    region: "محافظة شمال الشرقية",
    image: ainAlkhaleejImg,
    cuisine: "عُماني شعبي",
    priceRange: "budget",
    rating: 4.4,
    features: ["أكل شعبي", "أسعار مناسبة", "وجبات منزلية", "مناسب للعائلات"],
    mapUrl: "https://share.google/TJPr6xa8euLnu3HFh",
  },
  {
    id: "12",
    name: "Bin Ateeq Restaurant",
    nameAr: "مطعم بن عتيق للمأكولات العمانية",
    description: "يُعد مطعم بن عتيق من أشهر المطاعم العمانية في محافظة ظفار، ويتخصص في تقديم المأكولات العمانية الأصيلة بنكهة ظفارية مميزة. يشتهر المطعم بأطباقه التقليدية مثل المندي والمضبي والهريس، ويتميز بجودة المكونات والطعم الأصيل الذي يعكس تراث المطبخ العماني. يحظى المطعم بشعبية كبيرة بين السكان المحليين والسياح على حد سواء.",
    city: "صلالة",
    region: "محافظة ظفار",
    image: binAteeqImg,
    cuisine: "عُماني تقليدي",
    priceRange: "budget",
    rating: 4.6,
    features: ["مأكولات عمانية أصيلة", "مندي ومضبي", "أسعار مناسبة", "شعبية عالية"],
    mapUrl: "https://maps.app.goo.gl/vmXmWTYzsyyejR6u6",
  },
  {
    id: "13",
    name: "Café Bateel",
    nameAr: "كافيه بتيل",
    description: "كافيه بتيل في الموج مسقط يقدم تجربة فاخرة تجمع بين القهوة المختصة والمأكولات العالمية الراقية في أجواء أنيقة. يشتهر بتمور بتيل الفاخرة والشوكولاتة الفريدة، بالإضافة إلى الإفطار والغداء والمعجنات الطازجة. يتميز بإطلالته على الموج وجلساته الداخلية والخارجية المريحة.",
    city: "الموج مسقط، ولاية بوشر",
    region: "محافظة مسقط",
    image: cafeBateelImg,
    cuisine: "مقهى عالمي فاخر",
    priceRange: "expensive",
    rating: 4.7,
    features: ["تمور فاخرة", "شوكولاتة بتيل", "قهوة مختصة", "إفطار ومعجنات", "إطلالة بحرية"],
    mapUrl: "https://maps.app.goo.gl/nrtWYWLSrpDmGjr98",
  },
  {
    id: "14",
    name: "D'Arcy's Kitchen",
    nameAr: "دارسي كيتشن",
    description: "مطعم ومقهى أنيق يقع في شاطئ القرم بمسقط، يتميز بأجوائه الدافئة وجلساته الخارجية الملونة المحاطة بالنباتات. يقدم قائمة متنوعة تشمل الإفطار والغداء والمأكولات الأوروبية والمحلية، بالإضافة إلى المعجنات الطازجة والقهوة المختصة. وجهة مفضلة للعائلات والأصدقاء.",
    city: "شاطئ القرم، ولاية بوشر",
    region: "محافظة مسقط",
    image: darcysKitchenImg,
    cuisine: "أوروبي متنوع",
    priceRange: "moderate",
    rating: 4.6,
    features: ["إفطار ومعجنات", "جلسات خارجية", "قهوة مختصة", "أجواء عائلية", "مأكولات أوروبية"],
    mapUrl: "https://maps.app.goo.gl/DHA1aC3LYTw65xDM9",
  },
];
