import type { HikingTrip } from "@shared/schema";

export const hikingTrips: HikingTrip[] = [
  {
    id: "1",
    name: "Jebel Shams Summit",
    nameAr: "قمة جبل شمس",
    description: "رحلة هايكنق مثيرة إلى أعلى قمة في عُمان. استمتع بمناظر خلابة للوادي الأخضر وتجربة التخييم تحت النجوم في واحدة من أجمل المواقع الطبيعية.",
    location: "جبل شمس",
    region: "الداخلية",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?q=80&w=800",
    gallery: [
      "https://images.unsplash.com/photo-1551632811-561732d1e306?q=80&w=800",
    ],
    difficulty: "hard",
    duration: "يومين / ليلة واحدة",
    distance: "12 كم",
    price: 45,
    includes: ["مرشد سياحي", "وجبة غداء", "معدات التخييم", "نقل من مسقط", "إفطار"],
    rating: 4.9,
    phone: "+968 9123 4567",
  },
  {
    id: "2",
    name: "Wadi Shab Adventure",
    nameAr: "مغامرة وادي شاب",
    description: "رحلة سباحة وهايكنق في أجمل أودية عُمان. اكتشف الكهوف المخفية والشلالات الطبيعية والبرك الفيروزية في مغامرة لا تُنسى.",
    location: "وادي شاب",
    region: "جنوب الشرقية",
    image: "https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?q=80&w=800",
    gallery: [
      "https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?q=80&w=800",
    ],
    difficulty: "moderate",
    duration: "يوم واحد",
    distance: "5 كم",
    price: 25,
    includes: ["مرشد سياحي", "قارب", "وجبة غداء", "معدات السباحة", "نقل"],
    rating: 4.8,
    phone: "+968 9234 5678",
  },
  {
    id: "3",
    name: "Jabal Akhdar Trek",
    nameAr: "رحلة الجبل الأخضر",
    description: "اكتشف جمال الجبل الأخضر مع ممرات المشي القديمة بين القرى التراثية ومزارع الورد والرمان. استمتع بالمناخ البارد والإطلالات الرائعة.",
    location: "الجبل الأخضر",
    region: "الداخلية",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800",
    gallery: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800",
    ],
    difficulty: "moderate",
    duration: "يوم واحد",
    distance: "8 كم",
    price: 35,
    includes: ["مرشد محلي", "غداء تقليدي", "زيارة قرى", "شاي عماني", "نقل 4x4"],
    rating: 4.7,
    phone: "+968 9345 6789",
  },
  {
    id: "4",
    name: "Wadi Bani Khalid",
    nameAr: "وادي بني خالد",
    description: "رحلة استرخاء وسباحة في برك وادي بني خالد الصافية. مثالي للعائلات مع مناظر طبيعية خلابة وكهوف مدهشة للاستكشاف.",
    location: "وادي بني خالد",
    region: "شمال الشرقية",
    image: "https://images.unsplash.com/photo-1501555088652-021faa106b9b?q=80&w=800",
    gallery: [
      "https://images.unsplash.com/photo-1501555088652-021faa106b9b?q=80&w=800",
    ],
    difficulty: "easy",
    duration: "يوم واحد",
    distance: "3 كم",
    price: 20,
    includes: ["مرشد سياحي", "وجبة غداء", "نقل", "دخول الكهوف"],
    rating: 4.6,
    phone: "+968 9456 7890",
  },
  {
    id: "5",
    name: "Snake Canyon",
    nameAr: "وادي الثعبان",
    description: "مغامرة تسلق وقفز في وادي الثعبان الشهير. تحدي مثير للمغامرين مع تسلق الصخور والقفز في البرك والسباحة عبر الممرات الضيقة.",
    location: "وادي الأفاعي",
    region: "الداخلية",
    image: "https://images.unsplash.com/photo-1533240332313-0db49b459ad6?q=80&w=800",
    gallery: [
      "https://images.unsplash.com/photo-1533240332313-0db49b459ad6?q=80&w=800",
    ],
    difficulty: "expert",
    duration: "يوم واحد",
    distance: "4 كم",
    price: 55,
    includes: ["مرشد خبير", "معدات السلامة", "حبال التسلق", "وجبة غداء", "تأمين", "نقل"],
    rating: 4.9,
    phone: "+968 9567 8901",
  },
  {
    id: "6",
    name: "Desert Safari & Camping",
    nameAr: "سفاري وتخييم صحراوي",
    description: "تجربة صحراوية كاملة في رمال الشرقية. قيادة على الكثبان الرملية، ركوب الجمال، عشاء تحت النجوم، والتخييم في خيام تقليدية.",
    location: "رمال الشرقية",
    region: "شمال الشرقية",
    image: "https://images.unsplash.com/photo-1542401886-65d6c61db217?q=80&w=800",
    gallery: [
      "https://images.unsplash.com/photo-1542401886-65d6c61db217?q=80&w=800",
    ],
    difficulty: "easy",
    duration: "يومين / ليلة واحدة",
    distance: "غير محدد",
    price: 65,
    includes: ["نقل 4x4", "ركوب جمال", "عشاء شواء", "تخييم", "إفطار", "مشاهدة النجوم"],
    rating: 4.8,
    phone: "+968 9678 9012",
  },
  {
    id: "7",
    name: "Salalah Khareef Trek",
    nameAr: "رحلة خريف صلالة",
    description: "اكتشف سحر موسم الخريف في صلالة مع رحلات المشي في الجبال الخضراء والشلالات والعيون الطبيعية. تجربة استثنائية في أجواء استوائية.",
    location: "صلالة",
    region: "ظفار",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=800",
    gallery: [
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=800",
    ],
    difficulty: "easy",
    duration: "يوم واحد",
    distance: "6 كم",
    price: 30,
    includes: ["مرشد محلي", "زيارة الشلالات", "وجبة غداء", "جوز الهند الطازج", "نقل"],
    rating: 4.7,
    phone: "+968 9789 0123",
  },
  {
    id: "8",
    name: "Musandam Dhow Cruise",
    nameAr: "رحلة مسندم البحرية",
    description: "رحلة بحرية على متن قارب تقليدي في فيوردات مسندم الخلابة. سباحة، غطس، صيد أسماك، ومشاهدة الدلافين في مياه صافية كريستالية.",
    location: "مسندم",
    region: "مسندم",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800",
    gallery: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800",
    ],
    difficulty: "easy",
    duration: "يوم واحد",
    distance: "غير محدد",
    price: 40,
    includes: ["قارب داو", "غداء بحري", "معدات الغطس", "صيد أسماك", "مشروبات"],
    rating: 4.9,
    phone: "+968 9890 1234",
  },
];

export const getDifficultyAr = (difficulty: string) => {
  const map: Record<string, string> = {
    easy: "سهل",
    moderate: "متوسط",
    hard: "صعب",
    expert: "للخبراء",
  };
  return map[difficulty] || difficulty;
};

export const getDifficultyColor = (difficulty: string) => {
  const map: Record<string, string> = {
    easy: "bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400",
    moderate: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400",
    hard: "bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-400",
    expert: "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400",
  };
  return map[difficulty] || "";
};
