import type { Taxi } from "@shared/schema";
import ferryImg from "@/assets/ferry-oman.png";
import ferryHormuzImg from "@/assets/ferry-hormuz.png";
import ferryHallaniyatImg from "@/assets/ferry-hallaniyat.png";
import ferrySauqrahImg from "@/assets/ferry-sauqrah.png";
import vanImg from "@/assets/van-shouma.png";
import taxiRegularImg from "@/assets/taxi-regular.png";
import taxiLuxuryImg from "@/assets/taxi-luxury.png";

export const taxis: Taxi[] = [
  {
    id: "1",
    name: "Regular Taxi",
    nameAr: "تاكسي عادي",
    description: "خدمة تاكسي عادية بأسعار معقولة. سيارات مريحة ومكيفة مع سائقين محترفين لتوصيلك إلى وجهتك بأمان.",
    city: "جميع المناطق",
    region: "عُمان",
    image: taxiRegularImg,
    vehicleType: "تاكسي عادي",
    pricePerKm: 0.3,
    rating: 4.5,
    features: ["تكييف", "سائق محترف", "أسعار معقولة", "متوفر 24/7"],
    phone: "+968 24 777 888",
  },
  {
    id: "2",
    name: "Luxury Taxi",
    nameAr: "تاكسي فاخر",
    description: "خدمة تاكسي فاخرة للمناسبات الخاصة ورجال الأعمال. سيارات فارهة مع سائقين محترفين بزي رسمي وخدمة متميزة.",
    city: "جميع المناطق",
    region: "عُمان",
    image: taxiLuxuryImg,
    vehicleType: "تاكسي فاخر",
    pricePerKm: 0.8,
    rating: 4.9,
    features: ["سيارات فارهة", "واي فاي", "مشروبات مجانية", "سائق بزي رسمي"],
    phone: "+968 24 600 600",
  },
  {
    id: "3",
    name: "Van",
    nameAr: "فان",
    description: "سيارات فان واسعة للعائلات والمجموعات. تتسع حتى 7 ركاب مع مساحة كافية للأمتعة. مثالية للرحلات العائلية.",
    city: "جميع المناطق",
    region: "عُمان",
    image: vanImg,
    vehicleType: "فان",
    pricePerKm: 0.5,
    rating: 4.6,
    features: ["7 مقاعد", "مساحة أمتعة", "مقاعد أطفال", "تكييف قوي"],
    phone: "+968 24 555 555",
  },
  {
    id: "4",
    name: "Shana Ferry",
    nameAr: "شنّة",
    description: "عبارة شنّة للتنقل البحري. رحلات منتظمة مع إطلالات خلابة على البحر ومرافق مريحة.",
    city: "شنّة",
    region: "عُمان",
    image: ferryImg,
    vehicleType: "عبارة",
    pricePerKm: 1.0,
    rating: 4.7,
    features: ["رحلات بحرية", "مناظر طبيعية", "مقصورات مريحة", "مطعم على متنها"],
    phone: "+968 24 900 900",
  },
  {
    id: "5",
    name: "Masirah Jewel Ferry",
    nameAr: "جوهرة مصيرة",
    description: "عبارة جوهرة مصيرة للتنقل إلى جزيرة مصيرة. رحلات منتظمة مع خدمات متميزة.",
    city: "مصيرة",
    region: "جنوب الشرقية",
    image: ferryImg,
    vehicleType: "عبارة",
    pricePerKm: 1.0,
    rating: 4.8,
    features: ["رحلات بحرية", "مناظر طبيعية", "مقصورات مريحة", "مطعم على متنها"],
    phone: "+968 24 900 901",
  },
  {
    id: "6",
    name: "Hallaniyat Ferry",
    nameAr: "الحلانيات",
    description: "عبارة الحلانيات للتنقل إلى جزر الحلانيات. رحلات بحرية مميزة مع مناظر خلابة.",
    city: "الحلانيات",
    region: "ظفار",
    image: ferryHallaniyatImg,
    vehicleType: "عبارة",
    pricePerKm: 1.2,
    rating: 4.6,
    features: ["رحلات بحرية", "مناظر طبيعية", "مقصورات مريحة", "مطعم على متنها"],
    phone: "+968 24 900 902",
  },
  {
    id: "7",
    name: "Sauqrah Ferry",
    nameAr: "صوقرة",
    description: "عبارة صوقرة للنقل البحري. خدمة موثوقة مع رحلات منتظمة.",
    city: "صوقرة",
    region: "ظفار",
    image: ferrySauqrahImg,
    vehicleType: "عبارة",
    pricePerKm: 1.0,
    rating: 4.5,
    features: ["رحلات بحرية", "مناظر طبيعية", "مقصورات مريحة", "مطعم على متنها"],
    phone: "+968 24 900 903",
  },
  {
    id: "8",
    name: "Hormuz Ferry",
    nameAr: "هرمز",
    description: "عبارة هرمز للتنقل البحري إلى مضيق هرمز. رحلات مميزة مع إطلالات رائعة.",
    city: "مسندم",
    region: "مسندم",
    image: ferryHormuzImg,
    vehicleType: "عبارة",
    pricePerKm: 1.5,
    rating: 4.7,
    features: ["رحلات بحرية", "مناظر طبيعية", "مقصورات مريحة", "مطعم على متنها"],
    phone: "+968 24 900 904",
  },
];
